<?php
/**
 * @file
 * Emulate the display of the printed class timetable, with links to unit
 * descriptions.
 */

/**
 * Implements hook_menu().
 */
function uft_timetable_menu() {
  // Register the path for the timetable view.
  $items['timetable']  = array(
    'title'            => 'Timetables',
    'type'             => MENU_NORMAL_ITEM,
    'page callback'    => 'drupal_render_page',
    'page arguments'   => array('uft_timetable_display'),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Function to query and display timetable data.
 */
function uft_timetable_display() {
  $today = getdate();
  $current_year = $today['year'];

  // TODO Display options:
  // - Year
  // - Semester
  // - Courses

  // TODO Build the database query.
  $query = 'select entity_id from field_data_field_timetable_year
    where field_timetable_year_value = :year';

  // TODO Results of query.
  $results = db_query($query,
    array(':year' => $current_year)
  );
  foreach ($results as $record) {
    print $record->entity_id . "\n";
  }

  // TODO Format the output.

}
